# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Loaa2CgpG05S44S1FK0xBAjaR5tNbd8A
"""

import numpy as np
from scipy.stats import bernoulli
import random
sample_size = 100000
E, not_E = 0, 0
prob_E = 0.05
sample = bernoulli.rvs(size = sample_size, p = prob_E)
for i in range(sample_size):
  if sample[i] == 1:
    E += 1
  elif sample[i] == 0:
    not_E += 1
p_E = E/sample_size
p_not_E = not_E/sample_size
print("For the given probability of P(E) = %f, the probability of not E i.e, P(E') = %f"%(p_E, p_not_E))
print("which is approximately equal to the theoretical value 0.95")

